# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20161117_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
